// AUTH
export const LOGIN_LOADING = "LOGIN_LOADING"
export const LOGIN_AS_USER = "LOGIN_AS_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// ERROR
export const GENERIC_ERROR = "GENERIC_ERROR"

// FILES
export const LOAD_FILES = "LOAD_FILES"
export const LOAD_FILES_SUCCESS = "LOAD_FILES_SUCCESS"
export const LOAD_FILES_ERROR = "LOAD_FILES_ERROR"
export const GET_BALANCE = "GET_BALANCE"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const PURCHASE = "PURCHASE"
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const DOWNLOAD = "DOWNLOAD"
export const DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS"

// SCATTER
export const CONNECT_SCATTER = "CONNECT_SCATTER"
export const CONNECT_SCATTER_SUCCESS = "CONNECT_SCATTER_SUCCESS"
export const CONNECT_SCATTER_ERROR = "CONNECT_SCATTER_ERROR"
export const GET_SCATTER_IDENTITY = "GET_SCATTER_IDENTITY"
export const GET_SCATTER_IDENTITY_SUCCESS = "GET_SCATTER_IDENTITY_SUCCESS"